DROP DATABASE IF EXISTS USERTESTANDSONGS;

CREATE DATABASE USERTESTANDSONGS;

use USERTESTANDSONGS;

CREATE TABLE USER (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASS varchar(60) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE SONG (
    SONG_ID int NOT NULL AUTO_INCREMENT,
    SONG_NAME varchar(255) NOT NULL,
    PRIMARY KEY (SONG_ID)
);